const guestList = [
  'Shinta Roos',
  'Eric Roos',
  'Yuni Roos',
  'Ardi Roos',
  'Ria Roos',
  'Nigel Janssens',
  'Dylan Janssens',
  'Moïse Janssens',
  'Rob Janssens',
  'Priscilla Janssens',
  'Noortje Beckers',
  'Jamie de Ruijter',
  'Thimo',
  'Bianca Lust',
  'Tom Marcelis',
  'Demi Steenbergen',
  'Cansu Özdemir',
  'Kelvin Yiadom',
  'Erno Vreugdenhil',
  'Naomi Veldema',
  'Lesley Zut',
  'Naomi Philips',
  'Rawin Samadhan',
  'Lisa Pfleger',
  'Max Pootjes',
  'Arsen Demirci',
  'Fatih Kilic',
  'Varisha',
  'Mitch Grohe',
  'Ramin Erfani',
  'Nea',
  'Jeffrey Haverlag',
  'Karlijn Groenendijk',
  'Maarten Koops',
  'Gioia Loisi',
  'Melissa',
  'Sem Bolt',
  'Jay Medina',
  'Nico Benoist',
  'Bram van de Putte',
  'Lloyd Roos',
  'Ika Roos',
  'Johannes',
  'Manouk',
  'Cheston Roos',
  'Ely',
  'Tom',
  'Claudia',
  'Jacqueline',
  'Andre',
  'Gideon',
  'Rebecca Kalkhoven',
  'Edwin Kramer',
  'Enung Kalkhoven',
  'Ron Kalkhoven',
  'Paula Janssens',
  'Rik',
  'Djoy Boer',
  'Indy Boer',
  'Marianne',
  'Walter',
  'Anniek',
  'Sil',
  'Jonas',
  'Sari',
  'Nancy',
  'Piet',
  'Marcelle',
  'Frank',
  'Linda',
  'Sig',
] as const

export default guestList
